"""
Stage 2 Primary: Metadata-Based SBPR Tree Classifier Module (src.sbpr_tree)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Scikit-Learn classification engine that assigns incoming confirmed corrosion FTIR
records to one of the 3 historical SBPR defect categories based on tabular metadata
(vehicle model, mileage warranty intervals, and subject complaint text keywords).

Features:
1. Model Selection & Comparison: Automatically trains both a single DecisionTreeClassifier
   and an ensemble RandomForestClassifier, performing 5-fold Stratified Cross-Validation
   to determine whether ensemble variance reduction yields meaningfully higher accuracy.
2. Plain-English Explainability (XAI):
   - Single Decision Tree: Walks the exact mathematical branching tree (`decision_path()`)
     to translate node split conditions into an unambiguous rule chain (e.g., "vehicle
     model = Model 28 AND subject mentions 'seat'").
   - Random Forest Ensemble: Identifies active instance features weighted by ensemble Gini
     feature importance to explain the majority vote (e.g., "Predicted SBPR mainly based
     on: subject keyword 'seat', vehicle model = Model 28").
"""

import os
import sys
import re
import logging
from typing import Dict, Any, List, Union, Tuple, Optional

import joblib
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score

from .utils import get_bundle_path

logger = logging.getLogger(__name__)

DEFAULT_MODEL_SAVE_PATH = os.path.join(get_bundle_path("models"), "models", "sbpr_tree.joblib")


def train_sbpr_tree(
    X: pd.DataFrame, 
    y: pd.Series, 
    feature_names: List[str], 
    save_path: str = DEFAULT_MODEL_SAVE_PATH
) -> Any:
    """
    Train and compare DecisionTreeClassifier vs. RandomForestClassifier on labeled SBPR data,
    perform 5-fold Stratified Cross-Validation, save the winning model artifact, and report metrics.

    Parameters
    ----------
    X : pd.DataFrame
        Numerical feature matrix generated by `sbpr_features.build_features()`.
    y : pd.Series
        Historical ground truth label vector (SBPR defect identifiers).
    feature_names : List[str]
        Column titles of X.
    save_path : str, optional
        Filesystem path to persist trained model package (.joblib).

    Returns
    -------
    best_clf : sklearn estimator
        Trained model selected based on cross-validated predictive performance and explainability.
    """
    os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
    logger.info(f"Training Stage 2 SBPR classifiers on {len(X)} historical samples ({X.shape[1]} features)...")

    # 1. Initialize candidate architectures
    # We constrain max_depth and min_samples_leaf on the decision tree to prevent overfitting
    # and maintain readable, succinct explanation tree paths.
    dt_clf = DecisionTreeClassifier(max_depth=8, min_samples_leaf=3, random_state=42, class_weight="balanced")
    rf_clf = RandomForestClassifier(n_estimators=100, max_depth=12, min_samples_leaf=2, random_state=42, class_weight="balanced", n_jobs=-1)

    # 2. Evaluate with Stratified K-Fold Cross-Validation
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    dt_scores = cross_val_score(dt_clf, X, y, cv=skf, scoring="accuracy")
    rf_scores = cross_val_score(rf_clf, X, y, cv=skf, scoring="accuracy")

    dt_mean_acc = np.mean(dt_scores)
    rf_mean_acc = np.mean(rf_scores)

    logger.info(f"  -> Decision Tree CV Accuracy  : {dt_mean_acc:.2%} (+/- {np.std(dt_scores):.2%})")
    logger.info(f"  -> Random Forest CV Accuracy  : {rf_mean_acc:.2%} (+/- {np.std(rf_scores):.2%})")

    # 3. Model Selection Decision Logic
    # Rationale: A single Decision Tree provides absolute interpretability by allowing us to trace an
    # exact sequential decision path. A Random Forest acts as a black-box voting ensemble.
    # Therefore, we prefer the single Decision Tree unless Random Forest demonstrates a meaningful
    # predictive advantage (>= 1.5% accuracy improvement).
    accuracy_gain = rf_mean_acc - dt_mean_acc
    if accuracy_gain >= 0.015:
        logger.info(f"Random Forest outperformed single tree by +{accuracy_gain:.2%}. Selecting RandomForestClassifier for robust accuracy.")
        best_clf = rf_clf
        model_type = "RandomForestClassifier"
    else:
        logger.info(f"Single Decision Tree achieved competitive accuracy (within {accuracy_gain:.2%}). Selecting DecisionTreeClassifier for exact path interpretability.")
        best_clf = dt_clf
        model_type = "DecisionTreeClassifier"

    # 4. Train winning estimator on entire dataset for maximum diagnostic vocabulary retention
    best_clf.fit(X, y)

    # Save complete artifact bundle to safeguard against feature schema drift during inference
    model_bundle = {
        "model": best_clf,
        "feature_names": feature_names,
        "classes": list(best_clf.classes_),
        "model_type": model_type,
        "cv_accuracy_mean": rf_mean_acc if best_clf == rf_clf else dt_mean_acc
    }
    joblib.dump(model_bundle, save_path)
    logger.info(f"Successfully saved Stage 2 Primary model bundle to '{save_path}'")

    return best_clf


def _format_feature_name_to_english(feat_name: str, is_active: bool = True) -> str:
    """Translate raw feature column identifiers into natural English diagnostic statements."""
    if feat_name.startswith("contains_"):
        keyword = feat_name.replace("contains_", "").replace("_", " ")
        return f"subject mentions '{keyword}'" if is_active else f"subject lacks keyword '{keyword}'"
    elif feat_name.startswith("model_"):
        model_name = feat_name.replace("model_", "").title()
        return f"vehicle model = {model_name}" if is_active else f"vehicle model is not {model_name}"
    elif feat_name.startswith("mileage_"):
        bucket = feat_name.replace("mileage_", "")
        return f"mileage in range {bucket}" if is_active else f"mileage outside range {bucket}"
    return f"{feat_name} {'active' if is_active else 'inactive'}"


def _explain_decision_tree_path(model: DecisionTreeClassifier, row_input: Union[pd.DataFrame, np.ndarray], feature_names: List[str]) -> str:
    """
    Walk a single Decision Tree's internal node branching structure (`model.decision_path()`)
    and convert the matched threshold inequalities into an explicit plain-English AND conjunction.
    """
    row_array = row_input.to_numpy(dtype=float) if isinstance(row_input, pd.DataFrame) else row_input
    node_indicator = model.decision_path(row_input)
    node_index = node_indicator.indices
    tree = model.tree_
    
    positive_reasons = []
    negative_reasons = []

    for node_id in node_index:
        # Stop upon terminating at leaf node
        if tree.children_left[node_id] == tree.children_right[node_id]:
            break
            
        feat_idx = tree.feature[node_id]
        threshold = tree.threshold[node_id]
        val = row_array[0, feat_idx]
        feat_name = feature_names[feat_idx]

        # In our binary 0/1 one-hot schema, val > threshold implies active attribute (1)
        if val > threshold:
            positive_reasons.append(_format_feature_name_to_english(feat_name, is_active=True))
        else:
            negative_reasons.append(_format_feature_name_to_english(feat_name, is_active=False))

    # Prioritize active positive attributes (e.g., "mentions 'seat' AND vehicle model = Model 28")
    # as they provide significantly more intuitive diagnostic explanations to service engineers
    # than long lists of absent attributes.
    if positive_reasons:
        # Limit to top 4 positive indicators for crisp readability
        return " AND ".join(positive_reasons[:4])
    elif negative_reasons:
        # Fall back to exclusion criteria if prediction relied solely on absent features
        return " AND ".join(negative_reasons[:3])
    else:
        return "Default root node classification baseline"


def _explain_random_forest_importance(model: RandomForestClassifier, row_array: np.ndarray, feature_names: List[str], predicted_label: str) -> str:
    """
    Generate plain-English diagnostic explanations for ensemble RandomForestClassifier predictions.
    
    Why this explanation approach was picked for Random Forest:
    ----------------------------------------------------------
    An ensemble Random Forest decides by aggregating majority voting across hundreds of randomized
    trees. Attempting to walk a single boolean decision path is mathematically impossible and misleading.
    Instead, evaluating overall Gini feature importances weighted by the specific instance's active
    attributes (`feature_value * feature_importance`) reliably extracts the predominant factors
    that guided the ensemble to vote for the predicted defect category.
    """
    importances = model.feature_importances_
    # Filter for features that are actually active (value > 0) in this specific FTIR record
    active_mask = row_array[0] > 0
    active_indices = np.where(active_mask)[0]

    if len(active_indices) == 0:
        return f"Predicted {predicted_label} based on background defect prevalence (no strong active metadata keywords found)."

    # Sort active features in descending order of their importance to the ensemble classifier
    sorted_active = sorted(active_indices, key=lambda idx: importances[idx], reverse=True)
    
    # Take top 3 highest impact features
    top_features = [feature_names[idx] for idx in sorted_active[:3]]
    
    formatted_phrases = []
    for feat in top_features:
        if feat.startswith("contains_"):
            kw = feat.replace("contains_", "").replace("_", " ")
            formatted_phrases.append(f"subject keyword '{kw}'")
        elif feat.startswith("model_"):
            mod = feat.replace("model_", "").title()
            formatted_phrases.append(f"vehicle model = {mod}")
        elif feat.startswith("mileage_"):
            m = feat.replace("mileage_", "")
            formatted_phrases.append(f"mileage in range {m}")
        else:
            formatted_phrases.append(feat)

    reasons_str = ", ".join(formatted_phrases)
    return f"Predicted {predicted_label} mainly based on: {reasons_str}."


def predict_sbpr_metadata(
    feature_row: Union[pd.Series, pd.DataFrame, Dict[str, Any], np.ndarray], 
    model: Union[Any, str] = DEFAULT_MODEL_SAVE_PATH, 
    feature_names: Optional[List[str]] = None
) -> Dict[str, Any]:
    """
    Predict SBPR defect classification and generating plain-English explanatory reasoning for a single FTIR record.

    Parameters
    ----------
    feature_row : pd.Series, pd.DataFrame, dict, or np.ndarray
        Single row of engineered tabular features corresponding to an FTIR record.
    model : scikit-learn estimator, dict bundle, or str file path
        Trained evaluation model or path to joblib checkpoint.
    feature_names : List[str], optional
        List of feature column names (if model is raw estimator rather than bundle).

    Returns
    -------
    Dict[str, Any]
        {
            "sbpr_no": str (predicted defect class, e.g., "SBIN201210B00011"),
            "confidence": float (softmax / voting consensus probability between 0 and 1),
            "reason": str (human-readable explanation of why this SBPR was picked)
        }
    """
    # 1. Resolve and load model artifact if necessary
    if isinstance(model, str):
        if not os.path.exists(model):
            raise FileNotFoundError(f"Saved model bundle not found at: {model}")
        model = joblib.load(model)

    if isinstance(model, dict):
        clf = model["model"]
        feature_names = model.get("feature_names", feature_names)
    else:
        clf = model

    if feature_names is None:
        raise ValueError("feature_names must be provided if passing a raw scikit-learn estimator.")

    # 2. Standardize feature_row into a 2D DataFrame shaped (1, num_features) with valid names
    if isinstance(feature_row, pd.Series):
        row_df = pd.DataFrame([feature_row], columns=feature_names).fillna(0)
    elif isinstance(feature_row, pd.DataFrame):
        row_df = feature_row.reindex(columns=feature_names, fill_value=0)
        if len(row_df) > 1:
            row_df = row_df.iloc[:1]  # Enforce single-row evaluation per specification
    elif isinstance(feature_row, dict):
        row_df = pd.DataFrame([feature_row], columns=feature_names).fillna(0)
    else:
        row_df = pd.DataFrame(np.array(feature_row, dtype=float).reshape(1, -1), columns=feature_names).fillna(0)

    row_array = row_df.to_numpy(dtype=float)

    # 3. Compute probability distribution and prediction
    probs = clf.predict_proba(row_df)[0]
    best_idx = np.argmax(probs)
    predicted_label = str(clf.classes_[best_idx])
    confidence_score = float(probs[best_idx])

    # 4. Generate plain-English reason based on active architecture
    if isinstance(clf, DecisionTreeClassifier):
        reason_str = _explain_decision_tree_path(clf, row_df, feature_names)
    elif isinstance(clf, RandomForestClassifier):
        reason_str = _explain_random_forest_importance(clf, row_array, feature_names, predicted_label)
    else:
        reason_str = f"Predicted {predicted_label} with confidence {confidence_score:.1%}."

    return {
        "sbpr_no": predicted_label,
        "confidence": confidence_score,
        "reason": reason_str,
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    from src.excel_io import read_ftir_sheet
    from src.sbpr_features import build_features

    print("=" * 68)
    print("  Stage 2 Primary: SBPR Metadata Tree Classifier & XAI Verification")
    print("=" * 68)

    # 1. Load historical training data
    excel_dir = os.path.join("data", "excel")
    if not os.path.isdir(excel_dir):
        print("Historical data/excel/ directory not found. Please verify setup.")
        sys.exit(1)

    files = sorted([f for f in os.listdir(excel_dir) if f.endswith(".xlsx") and not f.startswith(".")])
    print(f"Loading and aggregating {len(files)} historical workbooks from '{excel_dir}':")
    
    dfs = []
    for fname in files:
        fpath = os.path.join(excel_dir, fname)
        df_sub = read_ftir_sheet(fpath)
        
        # Assign historical ground truth label directly from spreadsheet filename
        match = re.search(r"(SBIN\d+[A-Z]\d+)", fname)
        sbpr_code = match.group(1) if match else "SBIN_UNKNOWN"
        df_sub["sbpr_no"] = sbpr_code
        dfs.append(df_sub)
        print(f"  -> Loaded '{fname}' with ground truth label [{sbpr_code}] ({len(df_sub)} rows)")

    df_master = pd.concat(dfs, ignore_index=True)
    print(f"\nAggregated Historical Dataset Shape: {df_master.shape}")

    # 2. Engineer features
    print("Engineering numerical feature matrix X from tabular metadata...")
    X, y, feature_names = build_features(df_master)
    print(f"Feature Matrix Shape: {X.shape} ({len(feature_names)} engineered attributes)")

    # 3. Train models, evaluate cross-validation accuracy, and save winner
    print("\n" + "-" * 68)
    best_model = train_sbpr_tree(X, y, feature_names, save_path=DEFAULT_MODEL_SAVE_PATH)
    print("-" * 68)

    # 4. Sanity check: evaluate sample predictions and examine readable reasons
    print("\n=== SAMPLE PREDICTION & READABLE REASONS SANITY CHECK ===")
    print("Testing inference on selected diverse rows across different defect categories:\n")

    # Pick 5 interesting row indices spanning the 3 defect categories
    indices_to_test = [0, 320, 500, 1000, 1600]
    for idx in indices_to_test:
        if idx >= len(df_master):
            continue
        raw_row = df_master.iloc[idx]
        feat_row = X.iloc[idx]
        actual_sbpr = y.iloc[idx]
        
        # Get complaint text summary for inspection
        subj_text = str(raw_row.get("Subject (English)") or raw_row.get("Customer Complaint") or "N/A").strip()
        if len(subj_text) > 50:
            subj_text = subj_text[:47] + "..."

        result = predict_sbpr_metadata(feat_row, best_model, feature_names)

        print(f"Row #{idx:4d} | Actual: [{actual_sbpr}] -> Predicted: [{result['sbpr_no']}] (Confidence: {result['confidence']:.1%})")
        print(f"            | Raw Subject : \"{subj_text}\"")
        print(f"            | Explanation : {result['reason']}")
        print("-" * 68)
    print("=" * 68)
